### ISSUE TITLE
Can I use my free time to contribute to this module?

### ISSUE THREAD

**Issue by renanbastos93** [gofiber/redirect#1]
I want to improve my Go skills. Do you have something expect of redirect module?

**Comment by Fenny** [comment]
It should have the same setup +/- like https://github.com/gofiber/rewrite

But instead of rewriting the url, it should redirect using `c.Redirect`. 

Thanks!

**Comment by renanbastos93** [comment]
> It should have the same setup +/- like https://github.com/gofiber/rewrite
> 
> But instead of rewriting the url, it should redirect using `c.Redirect`.
> 
> Thanks!

I made a small first commit: https://github.com/gofiber/redirect/pull/2

**Comment by Fenny** [comment]
Merged 👍

**Comment by renanbastos93** [comment]
> Merged 👍

Thanks @Fenny see ya
