### ISSUE TITLE
Add Test for Filter Parameter

### ISSUE THREAD

**Issue by alexfinnarn** [gofiber/redirect#43]
Hello, 

I came to this project via the main org page, https://github.com/gofiber, and noticed this Redirect middleware that I didn't see before. It's exactly what I was looking for but didn't see in https://github.com/gofiber/fiber/blob/master/.github/README.md#-external-middleware. 

I'm not sure if this project is ready to add to the main readme, but first I think it should have a test for the Filter feature. I didn't know it existed except via the source code. 

I'm pretty new to Go, but I think I could add two tests for the Filter feature; however, I'm not sure what the status of this repo is based on the one other issue created over a year ago...so I figured I would ask about project status and plans first.

**Comment by hi019** [comment]
Before Fiber v2, we moved all he middlewares that didn't have third party dependencies from their own repository to the fiber/middleware folder. I'm not sure why this one wasn't transferred, but I think we should do that.

**Comment by WLun001** [comment]
[helmet](https://github.com/gofiber/helmet), [keyauth](https://github.com/gofiber/keyauth), and [rewrite](https://github.com/gofiber/rewrite) didn't have third party dependencies too.

**Comment by ReneWerner87** [comment]
yes exactly, the selection of the core middlewares was based on how likely it is that most people will use this middleware

all not often used special middlewares were moved to separate repositories

**Comment by ReneWerner87** [comment]
@hi019 would say that the redirect middleware is not used too often either, the only thing i would adjust is that it is found in the enumeration of external middlewares

**Comment by gaby** [comment]
Closed via #82
